name: BerkeleyaiHack
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=openblas
  - brotli-python=1.0.9=py39h313beb8_8
  - ca-certificates=2024.3.11=hca03da5_0
  - certifi=2024.6.2=py39hca03da5_0
  - fastapi=0.103.0=py39hca03da5_0
  - filelock=3.13.1=py39hca03da5_0
  - freetype=2.12.1=h1192e45_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py39h8c48613_0
  - idna=3.7=py39hca03da5_0
  - jinja2=3.1.4=py39hca03da5_0
  - jpeg=9e=h80987f9_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py39h80987f9_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py39hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.2.1=py39hca03da5_0
  - numpy=1.26.4=py39h3b2db8e_0
  - numpy-base=1.26.4=py39ha9811e2_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.14=h80987f9_0
  - pillow=10.3.0=py39h80987f9_0
  - pip=24.0=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.19=hb885b13_1
  - pytorch=2.3.1=py3.9_0
  - pyyaml=6.0.1=py39h80987f9_0
  - readline=8.2=h1a28f6b_0
  - setuptools=69.5.1=py39hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - starlette=0.27.0=py39hca03da5_0
  - sympy=1.12=py39hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - torchaudio=2.3.1=py39_cpu
  - torchvision=0.18.1=py39_cpu
  - typing_extensions=4.11.0=py39hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py39hca03da5_0
  - wheel=0.43.0=py39hca03da5_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.5=hd90d995_2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.4.0
      - charset-normalizer==3.3.2
      - distro==1.9.0
      - exceptiongroup==1.2.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-core==0.2.9
      - langchain-openai==0.1.9
      - langsmith==0.1.81
      - openai==1.35.3
      - orjson==3.10.5
      - packaging==24.1
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - python-dotenv==1.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - sniffio==1.3.1
      - tenacity==8.4.1
      - tiktoken==0.7.0
      - tqdm==4.66.4
      - typing-extensions==4.12.2
prefix: /opt/anaconda3/envs/BerkeleyaiHack
